"""Component-based prompt assembly.

A prompt is composed from three orthogonal components, each a nuisance factor
we want the model to be invariant to:

    role    : whether we tell the model it is a domain expert   {none, expert}
              (delivered as a system message when present)
    task    : the wording of the instruction (two paraphrases)  {v1, v2}
    format  : how the answer should be structured               {json, free}

Holding the *meaning* fixed while varying surface form lets us measure how much
each component perturbs the output. Variants are generated by the cartesian
product, each carrying a stable ``variant_id`` and a content hash so results
are joinable and reproducible.

Sub-themes are requested as free text (open, inductive discovery) — the prompt
does not impose a vocabulary. What is requested (free-text themes) is held
constant across the json/free contrast so that factor is purely about output
structure, not about what information is asked for.
"""

from __future__ import annotations

import hashlib
import itertools
from dataclasses import dataclass

from .config import Topic

# --------------------------------------------------------------------------
# Component levels
# --------------------------------------------------------------------------
ROLE_LEVELS = ("none", "expert")
TASK_LEVELS = ("v1", "v2")
FORMAT_LEVELS = ("json", "free")

# The 5-topic cap lives in the task wording ("Give at most N sub-topics"). This
# level is ``v1`` with that sentence removed, so it is the clean treatment for
# testing whether the cap inflates the topic count. It is deliberately NOT in
# ``TASK_LEVELS`` — the default grid must stay unchanged — and is run only via
# ``build_uncapped_variants`` / ``run.uncapped_plan``. Because the task text
# differs it gets a fresh ``prompt_hash``, so it never collides with the cached
# capped cells. Parse-time cap and token budget for this arm are widened in
# ``run.py`` (keyed off this same label).
TASK_UNCAPPED = "v1_nocap"

_PLACEHOLDER = "{{SPEECH}}"


def _role_block(level: str, topic: Topic) -> str:
    if level == "none":
        return ""
    if level == "expert":
        return (
            f"You are an expert analyst of {topic.name} policy in the United "
            f"Kingdom, with a deep understanding of parliamentary debate."
        )
    raise ValueError(f"unknown role level {level!r}")


def _topic_ref(topic: Topic) -> str:
    """How the construct is named in the task: bare name, or name + definition."""
    if not (topic.description or "").strip():
        return topic.name
    return f"{topic.name} — that is, {topic.description}"


def _task_block(level: str, topic: Topic) -> str:
    n = topic.max_subthemes
    ref = _topic_ref(topic)
    if level == "v1":
        return (
            f"Determine whether the parliamentary speech below substantively "
            f"discusses {ref} — rather "
            f"than merely mentioning it in passing.\n"
            f"If it does, identify the specific sub-topics of {topic.name} that "
            f"it discusses. Describe each sub-topic in your own words as a short "
            f"phrase (a few words). Give at most {n} sub-topics.\n"
            f"Also provide the single most relevant verbatim quotation from "
            f"the speech as supporting evidence."
        )
    if level == "v2":
        scope = (
            f"Treat {topic.name} as: {topic.description}."
            if (topic.description or "").strip()
            else f"Treat the topic as {topic.name}."
        )
        return (
            f"Read the parliamentary speech below. Decide if {topic.name} is a "
            f"substantive subject of the speech and not just a passing "
            f"reference. {scope}\n"
            f"When it is a substantive subject, list the particular aspects of "
            f"{topic.name} it covers, each as a brief free-text label of a few "
            f"words. Provide no more than {n} such labels.\n"
            f"Include a short supporting quotation taken word-for-word from "
            f"the speech."
        )
    if level == TASK_UNCAPPED:
        # ``v1`` verbatim with the "Give at most N sub-topics" sentence removed:
        # no instruction about *how many* sub-topics, so the count is the model's
        # rather than ours. Everything else is held identical to v1 so the only
        # difference from the cached capped cells is the cap itself.
        return (
            f"Determine whether the parliamentary speech below substantively "
            f"discusses {ref} — rather "
            f"than merely mentioning it in passing.\n"
            f"If it does, identify the specific sub-topics of {topic.name} that "
            f"it discusses. Describe each sub-topic in your own words as a short "
            f"phrase (a few words).\n"
            f"Also provide the single most relevant verbatim quotation from "
            f"the speech as supporting evidence."
        )
    raise ValueError(f"unknown task level {level!r}")


def _format_block(level: str) -> str:
    if level == "json":
        return (
            "Respond with a single JSON object and nothing else, with exactly "
            "these keys:\n"
            '  "mentions_topic": true or false,\n'
            '  "subthemes": an array of short free-text phrases (empty if '
            "mentions_topic is false),\n"
            '  "evidence_quote": a string (empty if mentions_topic is false).'
        )
    if level == "free":
        # The "no format instruction" condition: deliberately unstructured, so
        # its parse-failure rate reflects the true cost of omitting format.
        return ""
    raise ValueError(f"unknown format level {level!r}")


# --------------------------------------------------------------------------
# Variant
# --------------------------------------------------------------------------
@dataclass(frozen=True)
class PromptVariant:
    """One point in the role x task x format design space."""

    role: str
    task: str
    output_format: str
    topic: Topic

    @property
    def variant_id(self) -> str:
        return f"role={self.role}|task={self.task}|format={self.output_format}"

    @property
    def definition(self) -> str:
        """Which construct definition this variant carries.

        Kept out of ``variant_id`` on purpose: ``variant_id`` names a cell in
        the nuisance-factor grid, and the definition is a separate axis (one we
        expect to matter). Keeping them separate also means the ids already
        written to the results log stay correct.
        """
        return self.topic.definition_id

    def _system_text(self) -> str:
        """The role component, which is delivered as a system message."""
        return _role_block(self.role, self.topic)

    def _user_template(self) -> str:
        """The user message body (task + format + speech placeholder)."""
        parts = [
            _task_block(self.task, self.topic),
            _format_block(self.output_format),
            f"Speech:\n{_PLACEHOLDER}",
        ]
        return "\n\n".join(p for p in parts if p)

    def _template(self) -> str:
        """Identity string for hashing: system + user, so the hash reflects
        exactly what is sent (role placement included), independent of which
        speech it scores."""
        sys = self._system_text()
        body = self._user_template()
        return f"[system]\n{sys}\n\n[user]\n{body}" if sys else f"[user]\n{body}"

    @property
    def prompt_hash(self) -> str:
        return hashlib.sha1(self._template().encode("utf-8")).hexdigest()[:12]

    def render(self, speech_text: str) -> list[dict[str, str]]:
        """Render to OpenAI-style chat messages for a given speech. The role
        (when present) is a system message; the task/format/speech is a user
        message."""
        msgs: list[dict[str, str]] = []
        sys = self._system_text()
        if sys:
            msgs.append({"role": "system", "content": sys})
        body = self._user_template().replace(_PLACEHOLDER, speech_text)
        msgs.append({"role": "user", "content": body})
        return msgs


def build_variants(
    topic: Topic,
    *,
    roles: tuple[str, ...] = ROLE_LEVELS,
    tasks: tuple[str, ...] = TASK_LEVELS,
    formats: tuple[str, ...] = FORMAT_LEVELS,
) -> list[PromptVariant]:
    """Cartesian product of the requested component levels."""
    return [
        PromptVariant(role=r, task=t, output_format=f, topic=topic)
        for r, t, f in itertools.product(roles, tasks, formats)
    ]


def build_uncapped_variants(
    topic: Topic,
    *,
    roles: tuple[str, ...] = ("none",),
    formats: tuple[str, ...] = FORMAT_LEVELS,
) -> list[PromptVariant]:
    """The focused arm for the no-cap experiment: the uncapped task under the
    two output formats, role held at ``none`` and task paraphrase fixed.

    This deliberately varies only the factors that move the result (model, set
    by the caller, and output format) and holds the two lowest-impact factors
    (role, task paraphrase) constant, so the contrast against the already-cached
    capped cells (role=none, task=v1, same formats/models) isolates the cap.
    """
    return [
        PromptVariant(role=r, task=TASK_UNCAPPED, output_format=f, topic=topic)
        for r in roles for f in formats
    ]


def build_definition_variants(
    topics: list[Topic],
    *,
    roles: tuple[str, ...] = ("none",),
    formats: tuple[str, ...] = FORMAT_LEVELS,
    task: str = TASK_UNCAPPED,
) -> list[PromptVariant]:
    """The definition-sensitivity arm: one variant set per construct definition,
    run at the new default configuration (no role, no cap, both formats).

    The nuisance factors are held at the shipping default so the only thing
    varying across ``topics`` is the definition text. Because ``description`` is
    interpolated into the task block, each definition yields a distinct
    ``prompt_hash`` and therefore cannot collide with cached cells.
    """
    return [
        PromptVariant(role=r, task=task, output_format=f, topic=t)
        for t in topics for r in roles for f in formats
    ]
